name: Build and Push Multi-Arch Docker Image

on:
  push:
    branches: [ main ]

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: Pass SHA and Is_Release to Dockerfile Args
      run: |
        if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
          echo "IS_RELEASE=true" >> $GITHUB_ENV
        else
          echo "IS_RELEASE=false" >> $GITHUB_ENV
        fi

    - name: Set up QEMU (emulation)
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push for amd64 + arm64
      uses: docker/build-push-action@v5
      with:
        context: ./
        file: ./ledfx_docker/Dockerfile
        platforms: linux/amd64,linux/arm64
        push: true
        tags: ghcr.io/${{ github.repository_owner }}/ledfx:latest
        cache-from: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ledfx:latest
        cache-to: type=registry,ref=ghcr.io/${{ github.repository_owner }}/ledfx:latest,mode=max
        build-args: |
          GITHUB_SHA=${{ env.GITHUB_SHA }}
          IS_RELEASE=${{ env.IS_RELEASE }}