name: Upload MIDI Map
on:
  issues:
    types: [labeled]

jobs:
  Upload-Attachment:
    if: ${{ github.event.label.name == 'Upload to MIDI Collection' }}

    runs-on: ubuntu-latest
    steps:
    - name: Get MIDI Map File
      run:  |
        attachments=($(echo $url | awk -v RS=[\(] -v FS=[\)] 'NR>1{print $1}' ))
        echo ${attachments[1]}
        for i in "${attachments[@]}"
        do
          :
          echo $i
          curl -O $i
        done
        ls
      env:
        url: ${{github.event.issue.body}}
    - name: Upload MIDI Map File
      uses: SamKirkland/FTP-Deploy-Action@4.1.0
      with:
        server: midimap.ledfx.app
        username: ${{ secrets.MIDIMAP_UPLOAD_USERNAME }}
        password: ${{ secrets.MIDIMAP_UPLOAD_PASSWORD }}
